# Loop feature will be removed in version 2.11
---
- hosts: localhost
  become: true
  tasks:
   - name: Install list of packages
     yum:   #could be package as it works for all linux distributions
      name: ['httpd', 'wget', 'vim', 'zip', 'unzip'] #when working on ubuntu server, change yum to apt and delete httpd. 
...
